---
- name: Configure cisco acl ip management router
  hosts: R1
  connection: local
  gather_facts: false

  tasks:
    - name: load new acl ip management into device
      ios_config:
        lines:
          - permit tcp any any established
          - permit ip host 10.10.1.1 any
          - permit ip host 10.10.2.12 any
          - permit ip host 10.10.1.20 any
          - permit ip host 103.6.117.25 any
          - permit ip host 103.6.117.75 any
          - permit ip host 139.0.9.238 any
          - permit ip host 139.0.9.244 any
        parents: ip access-list extended 190
        match: exact

    - name: APPLY ACL
      ios_config:
        authorize: yes
        lines:
          - access-class 190 in
        parents: line vty 0 4

    - name: VERIFY ACL CONFIG
      ios_command:
        commands:
          - show ip access-list
        register: acl

    - debug: var=acl.stdout_lines

    - name: VERIFY ACL CONFIG
      ios_command:
        commands:
          - show ip access-list
      register: acl

    - debug: var=acl.stdout_lines
