---
- name: Test reachability to 10.10.1.1 using default vrf
  hosts: SWPALMA
  connection: local
  gather_facts: false  
  
  tasks:
    - name: ping
      ios_ping:
        dest: "{{ item }}"
        count: 5        # default
      with_items:
        - 10.10.1.1
      ignore_errors: yes
      register: result
