---
- name: Test reachability to 10.10.1.1
  hosts: R2junos
  connection: local
  gather_facts: no

  tasks:
    - name: text ping
      junos_command:
      commands: ping 10.10.1.1
      provider: "{{ cli }}"
